version: '3.3'

services:
  elasticsearch:
    image: elastic
    ports:
      - "9200:9200"  
      - "9300:9300"
    environment:
      - "xpack.security.enabled=false"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "transport.tcp.port=9300"
      - "transport.publish_host=127.0.0.1"
      - "transport.publish_port=9300"
  search:
    image: elo7/search
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9300
      - ELASTICSEARCH_CLUSTERNAME=elasticsearch
    depends_on:
      - elasticsearch
    links:
      - elasticsearch