version: '3.3'

services:
  elasticsearch:
    image: elo7/elastic
    ports:
      - "9200:9200"  
      - "9300:9300"
    environment:
      - "xpack.security.enabled=false"
      - "http.port=9200"
      - "transport.tcp.port=9300"
  search:
    image: elo7/search
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9300
      - "ELASTICSEARCH_CLUSTERNAME=elastic-cluster"
    depends_on:
      - elasticsearch