server:
  port: 8080
  context-path: /search

management:
  port: 8081
  context-path: /search

elasticsearch:
  host: localhost
  port: 9300
  clustername: elasticsearch
---

spring:
  profiles: container

